# Face and Eyes Detection Using Haar Cascade

# Importing Libraries

In [1]:
import cv2
import numpy as np
import time

In [2]:
cv2.__file__

'C:\\Users\\patel\\anaconda3\\lib\\site-packages\\cv2\\__init__.py'

### Initiating Classifiers

In [3]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

### Reading Image

In [4]:
img = cv2.imread('faces.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # will be fed to cascade
cv2.imshow("Original",img)
cv2.imshow("Grayscale",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Detecting Face

In [5]:
faces=face_cascade.detectMultiScale(gray,scaleFactor=1.3,minNeighbors=5)
print(faces)

[[234  25  85  85]
 [363  34  86  86]]


### Enclosing Face with Rectangle

In [6]:
x,y,w,h=faces[0]
img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Creating ROI of Face

In [7]:
roi_gray = gray[y:y+h, x:x+w]
roi_color = img[y:y+h, x:x+w]
cv2.imshow('ROI Gray (Face)',roi_gray)
cv2.imshow('ROI Color (Face)',roi_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
roi_color

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [221, 223, 224],
        ...,
        [ 99, 102, 100],
        [106, 112, 111],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 90, 113, 159],
        ...,
        [102, 111,  30],
        [104, 116,  28],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 88, 118, 167],
        ...,
        [102, 112,  29],
        [103, 115,  27],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

### Detecting Eyes and Enclosing them with Rectangles

In [8]:
eyes = eye_cascade.detectMultiScale(roi_gray)
print(eyes)

[[16 18 25 25]
 [41 22 24 24]]


In [9]:
for (ex,ey,ew,eh) in eyes:
    cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,255),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Multiple Faces in one image

In [9]:
img = cv2.imread('faces.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Original",img)
cv2.imshow("Grayscale",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Detecting All Faces and All Eyes

In [10]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
print("Number of Faces: ",len(faces))
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of Faces:  2
